### ISSUE TITLE
tinyint fields being reconized as string even after #83 fix

### ISSUE THREAD

**Issue by lahdirakram** [planetscale/airbyte-source#89]
hey im running the latest version of this repo and i still have tinyints mapped as strings even if it was corrected here #83. so i did a little change and it works fine now. could you investigate and add this change please ? 

in https://github.com/planetscale/airbyte-source/blob/8017ce1ec394fc8575673bc2dc9b42c1e251d3fb/cmd/internal/planetscale_edge_database.go#L132C1-L132C50
i changed this line 
`case strings.HasPrefix(mysqlType, "tinyint(1)"):`
to this one
`case strings.HasPrefix(mysqlType, "tinyint"):`

**Comment by Phanatic** [comment]
Hi @lahdirakram, 
I just made a new release of the airbyte source, can you please try your sync again and let us know if its still broken ?

I took a look at the issue and the current behavior and according to the tests, the behavior is correct:
 https://github.com/planetscale/airbyte-source/blob/8017ce1ec394fc8575673bc2dc9b42c1e251d3fb/cmd/internal/planetscale_edge_database_test.go#L228-L249

The usual flow for a Sync operation is : 
1.  The schema output is sent to airbyte so that airbyte can create columns on the destination accurately.
2. But the schema is not used for serialization. When serializing values, we depend on the JSON serializer in golang to accurately convert int64 to its JSON equivalent and so on. 

What is the destination you're using and how did you determine that we're sending strings for tinyint values?
Can you please reply with  the PlanetScale organization, database name and branch name so I can recreate your schema and see if tinyint values in your schema are being returned as strings?

**Comment by Phanatic** [comment]
Actually, we found the issue, @lahdirakram this will be fixed in https://github.com/planetscale/airbyte-source/pull/90

**Comment by Phanatic** [comment]
New release of the docker image is out too : https://hub.docker.com/layers/planetscale/airbyte-source/latest/images/sha256-c3ba199b08988be3b5f5a1b5c2e8dfaa3a96e0f90c513ed6a24d71b57fec6d8f?context=explore

**Comment by lahdirakram** [comment]
Thank you for your fast response. I've tested the release you made, and it's working fine. I appreciate your help!
